### ISSUE TITLE
pub score

### ISSUE THREAD

**Issue by Abhishek01039** [beximo/onboarding_screen#13]
<img width="786" alt="image" src="https://user-images.githubusercontent.com/56479665/117633181-6d7eb600-b19b-11eb-85fe-2b9caea02bb5.png">

Hey @woinbo 
can we use HTTPS here? (https://github.com/beximo/onboarding_screen#getting-started-1)

**Comment by woinbo** [comment]
> <img alt="image" width="786" src="https://user-images.githubusercontent.com/56479665/117633181-6d7eb600-b19b-11eb-85fe-2b9caea02bb5.png">
> 
> Hey @woinbo
> can we use HTTPS here? (https://github.com/beximo/onboarding_screen#getting-started-1)

Yaa, we can let me change this, Thanks for reminding me!

**Comment by Abhishek01039** [comment]
Thanks @woinbo

**Comment by woinbo** [comment]
@Abhishek01039 check pub scores it's full/full✌

**Comment by Abhishek01039** [comment]
Great work @woinbo
