### ISSUE TITLE
Image is not loaded in readme.md and more

### ISSUE THREAD

**Issue by Abhishek01039** [beximo/onboarding_screen#2]
1. Image is not loaded in readme.md file
2. print should not be there in product code
3. Better to use assert
4. Define the constructor first
5. Use const or final whenever possible 
6. Please follow the convention of file name in Dart

Thanks.

**Comment by Abhishek01039** [comment]
I would like to work on it.
if you allow.

**Comment by woinbo** [comment]
> I would like to work on it.
> if you allow.

Hmm, sure work on it😀! Thank you

**Comment by woinbo** [comment]
LGTM @Abhishek01039
